Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'