language: ruby
rvm:
  - "2.0.0"

deploy:
  provider: heroku
  app: danceparty911_v2
  api_key:   
  	secure: "egYEJM5S1nltmAVLY1A2U8RbuYUh1cYF3lzwnEAexWqW6OaCzW46YWQlZXHrsabwxep8fzVgik69v+TXFWnotuzKu/1NL3WqwwtElsND5q9gm83iqe3N5E5EIRxYlqm4+AvwFfH44So+/Gqtton4jkSDKp9kHRHTYDfmyXpo6BI="