Rails.application.config.assets.precompile += %w( div_animate.js )
Rails.application.config.assets.precompile += %w( navbar.css )
Rails.application.config.assets.precompile += %w( bootstrap.js )
Rails.application.config.assets.precompile += %w( play_thru/soundmanager2.js )
Rails.application.config.assets.precompile += %w( play_thru/page-player.js )